import features.conf

# Batch size: number of samples in a training/test/validation batch
BATCH_SIZE = 512
# Timesteps: number of keystrokes in a sequence
# (NOTE: Should be equal to the sequence length used when computing the dataset features)
TIMESTEPS = features.conf.SEQUENCE_LENGTH
# Number of features: 4 (HOLD_LATENCY, INTERKEY_LATENCY, PRESS_LATENCY, RELEASE_LATENCY)
NO_FEATURES = 4
# Input shape is (length of a keystroke sequence, number of features)
INPUT_SHAPE = (TIMESTEPS, NO_FEATURES)
# Number of dimensions in embedding vectors generated by LSTM tower network
EMBEDDING_DIMENSIONS = 128
# Naming prefix for
SIAMESE_NAME_PREFIX = "Siamese_RNN"
